<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>FuelStation</AssemblyName>
    <RootNamespace>FuelStation</RootNamespace>
    <UserSecretsId>7dbdd08d-1d80-4171-8b13-2eff2b6beb77</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\js\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FuelStation.DataLayer\FuelStation.DataLayer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="users.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>

</Project>
